services:
  ai_text_detector:
    container_name: ai_text_detector-python
    image: gabrielagapie/ai_text_detector_plublic_dataset-ai_text_detector
    build:
      context: .
      dockerfile:  ai_detect.Dockerfile
    ports:
      - "8080:8080"
    networks:
      - db
  ai_text_detector-front-end:
    container_name: ai_text_detector_front_end-react
    image: gabrielagapie/ai_text_detector_front_end-react
    build:
      context: frontend/react
      dockerfile:  Dockerfile
      args:
        api_base_url: http://localhost:8001
    ports:
      - "5173:5173"
    depends_on:
      - ai_text_detector
    restart: unless-stopped


networks:
  db:
    driver: bridge

volumes:
  db:

